# testing using CircleCI orb
# see https://on.cypress.io/circleci-orb

version: 2.1
orbs:
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1.26.0
  slack: circleci/slack@1.0.0

workflows:
  build:
   jobs:
   - cypress/run
